// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bike_analyser/:bike_id": {
    params: {
      "bike_id": string;
    };
  };
  "/auth/verify-email": {
    params: {};
  };
  "/bikes/new": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot": {
    params: {};
  };
  "/bikes": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/reset": {
    params: {};
  };
  "/sheds": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/bike_analyser/:bike_id" | "/auth/verify-email" | "/bikes/new" | "/register" | "/forgot" | "/bikes" | "/login" | "/reset" | "/sheds" | "/*";
  };
  "routes/[bike_analyser].$[bike_id]._index.jsx": {
    id: "routes/[bike_analyser].$[bike_id]._index";
    page: "/bike_analyser/:bike_id";
  };
  "routes/[auth].[verify-email]._index.jsx": {
    id: "routes/[auth].[verify-email]._index";
    page: "/auth/verify-email";
  };
  "routes/[bikes].[new]._index.jsx": {
    id: "routes/[bikes].[new]._index";
    page: "/bikes/new";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[forgot]._index.jsx": {
    id: "routes/[forgot]._index";
    page: "/forgot";
  };
  "routes/[bikes]._index.jsx": {
    id: "routes/[bikes]._index";
    page: "/bikes";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/[reset]._index.jsx": {
    id: "routes/[reset]._index";
    page: "/reset";
  };
  "routes/[sheds]._index.jsx": {
    id: "routes/[sheds]._index";
    page: "/sheds";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[bike_analyser].$[bike_id]._index": typeof import("./app/routes/[bike_analyser].$[bike_id]._index.jsx");
  "routes/[auth].[verify-email]._index": typeof import("./app/routes/[auth].[verify-email]._index.jsx");
  "routes/[bikes].[new]._index": typeof import("./app/routes/[bikes].[new]._index.jsx");
  "routes/[register]._index": typeof import("./app/routes/[register]._index.jsx");
  "routes/[forgot]._index": typeof import("./app/routes/[forgot]._index.jsx");
  "routes/[bikes]._index": typeof import("./app/routes/[bikes]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/[reset]._index": typeof import("./app/routes/[reset]._index.jsx");
  "routes/[sheds]._index": typeof import("./app/routes/[sheds]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};